version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'next'
    schedule:
      interval: 'weekly'
    groups:
      react:
        patterns:
          - 'react*'
      typescript:
        patterns:
          - '@types*'
          - 'ts*'
          - 'typescript*'
      oxc:
        patterns:
          - 'oxlint*'
          - 'oxfmt*'
      radix:
        patterns:
          - '@radix-ui*'
      vite|vitest:
        patterns:
          - 'vite*'
          - '@vite*'
      tailwind:
        patterns:
          - 'tailwind*'
          - '@tailwind*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
